package entity;

import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Scanner;

import org.apache.tomcat.util.security.MD5Encoder;

public class hackkerrank {

	public static String getMd5(String input)
    {
        try {
 
            // Static getInstance method is called with hashing MD5
            MessageDigest md = MessageDigest.getInstance("MD5");
 
            // digest() method is called to calculate message digest
            // of an input digest() return array of byte
            byte[] messageDigest = md.digest(input.getBytes());
            System.out.println(messageDigest);
            // Convert byte array into signum representation
            BigInteger no = new BigInteger(1, messageDigest);
            System.out.println(no);
            // Convert message digest into hex value
            String hashtext = no.toString(16);
            System.out.println(hashtext);
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
            return hashtext;
        }
 
        // For specifying wrong message digest algorithms
        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }
 
    // Driver code
    public static void main(String args[]) throws NoSuchAlgorithmException
    {
    	Scanner sc = new Scanner(System.in);
    	
        String input = sc.nextLine();
        System.out.println("Your HashCode Generated by MD5 is: " + getMd5(input));
        
        String a = sc.nextLine();
        String b = sc.nextLine();
        
        BigInteger a1 = new BigInteger(1,a.getBytes());
        
        System.out.println(a1.toString(16));
        BigInteger b1 = new BigInteger(1, b.getBytes());
        
        System.out.println(b1.toString(16));
    }
}
